# you can change the translator in here.
# translator list:
# - GoogleTranslator
# - ChatGptTranslator
# - MicrosoftTranslator
# - PonsTranslator
# - LingueeTranslator
# - MyMemoryTranslator
# - YandexTranslator
# - PapagoTranslator
# - DeeplTranslator
# - QcriTranslator
translator: GoogleTranslator
api_key: "" # if wanted by the translator

# these keys' values will not be translated
# if you want to translate all keys, make it like protected_keys: []
protected_keys:
  - material
  - id
  - slot
  - price
  - level
  - command
  - permissions
  - items
  - block
  - entity
  - sound
  - effect